

function manyTestsSynomyn() {
  //testing
  listArray = ['testArraySynonym', 'getKilledSynonym', 'getModifierSynonym', 'getHowBadSynonym', 'getSurprisedSynonym', 'pullItOffSynonym', 'couldBeWrongSynonym', 'workOnTheirGolfSwingSynonym', 'oldNewsSynonym', 'imSkepticalSynonym', 'betterThanExpectedSynonym', 'areKillingItSynonym', 'inShockWinningSynonym', 'delaySynonym','followRockiesFeed', 'goingToHurtSynonym', ]

  //Logger.log('array length = ' + listArray.length)
  for (i=0; i < 100; i++) {
    index = Math.floor(Math.random() * (listArray.length - 1))
    //Logger.log(index)
    list = listArray[index]    
    getSynonym(list)
  }
}

function returnRandomWordIndex(array) {
  index = Math.floor(Math.random() * (array.length - 1) + 0)
  //Logger.log(index)
  return index
}


function initAllSynonyms() {
  //available = allSynonymsHardcoded()
  used = {}
  available = allSynonymsHardcoded()

  output = []

  const availableArray = Object.keys(available).reduce((acc, key) => {
    acc.push({ [key]: available[key] });
    return acc;
  }, []);
  Logger.log(availableArray[0]);

  //seed 'used' with keys but no data
  const usedArray = Object.keys(available).reduce((acc, key) => {
    acc.push({ [key]: [] });
    return acc;
  }, []);
  Logger.log(usedArray[0]);  

  for (i=0; i < availableArray.length; i++) {
    output.push([JSON.stringify(availableArray[i]),JSON.stringify(usedArray[i])])
  }

  Logger.log(output[0]);

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Synonym Brainstorms");  
  sheet.getRange(2,1,output.length,2).setValues(output);
}

function readSynonymsLists() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Synonyms");
  listCount = sheet.getRange(1,4,1,1).getValue();
  //Logger.log(listCount)

  available = {}
  used = {}


  bothLists = sheet.getRange(2,1,listCount,2).getValues();
  //Logger.log(bothLists)

  for (let record of bothLists) {
    //Logger.log(record[0])
    aKey = Object.keys(JSON.parse(record[0]))[0]
    aValue = Object.values(JSON.parse(record[0]))[0]
    bKey = Object.keys(JSON.parse(record[1]))[0]
    bValue = Object.values(JSON.parse(record[1]))[0]
    //Logger.log(aKey)
    //Logger.log(aValue)
    available[aKey] = aValue
    used[bKey] = bValue
  }

  //Logger.log(available['testArraySynonym'])
  //Logger.log(used['testArraySynonym'])


  //available = JSON.parse(bothLists[0])
  //used = JSON.parse(bothLists[1])


  //Logger.log(available['followRockiesFeed'])

  //Logger.log(available)
  //Logger.log(used)

  return [available, used]
}

function orderKeys(obj) {

  var keys = Object.keys(obj).sort(function keyOrder(k1, k2) {
      if (k1 < k2) return -1;
      else if (k1 > k2) return +1;
      else return 0;
  });

  var i, after = {};
  for (i = 0; i < keys.length; i++) {
    after[keys[i]] = obj[keys[i]];
    delete obj[keys[i]];
  }

  for (i = 0; i < keys.length; i++) {
    obj[keys[i]] = after[keys[i]];
  }
  return obj;
}


function writeSynonymsLists(available, used) {
  output = []

  //Logger.log('writeSynonymsLists')
  //Logger.log(used)

  let availableArray = Object.keys(available).reduce((acc, key) => {
    acc.push({ [key]: available[key] });
    return acc;
  }, []);
  //Logger.log(availableArray[0]);

  availableArray = orderKeys(availableArray)

  //seed 'used' with keys but no data
  let usedArray = Object.keys(used).reduce((acc, key) => {
    acc.push({ [key]: used[key] });
    return acc;
  }, []);
  //Logger.log(usedArray);

  usedArray = orderKeys(usedArray)

  for (i=0; i < availableArray.length; i++) {
    output.push([JSON.stringify(availableArray[i]),JSON.stringify(usedArray[i])])
  }

  //Logger.log(output.length)
  //Logger.log(output[0]);

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Synonyms");  
  sheet.getRange(2,1,output.length,2).setValues(output);
}


function getSynonym(list, test) {
  let [available, used] = readSynonymsLists()
  //if list all used up, reset
  if (available[list] == null || available[list].length == 0 ) {
    available[list] = used[list]
    used[list] = []
  }

  //Logger.log(list + ' ' + available[list])
  index = returnRandomWordIndex(available[list])
  phrase = available[list].splice(index,1)[0]

  if (used[list] == null) {
    used[list] = []
    used[list].push(phrase)
  }
  else {
    used[list].push(phrase)
  }
  

  //Logger.log(`using phrase from ${list}: ${phrase}`)
  //Logger.log(available[list])
  //Logger.log(used[list])

  !test && writeSynonymsLists(available, used)

  return phrase;
}



function allSynonymsHardcoded() {
  all = {
      testArraySynonym: ['phrase 1', 'phrase 2', 'phrase 3'],
      getKilledSynonym: ['annihilated', 'assassinated', 'blacked out', 'blasted', 'blotted out', 'broken', 'brutalized', 'bumped off', 'busted', 'butchered', 'cracked', 'cut down', 'cut into pieces', 'damaged', 'decimated', 'defaced', 'demolished', 'destroyed', 'detonated', 'devastated', 'devoured', 'disintegrated', 'dismantled', 'dispatched', 'dissolved', 'done away with', 'done in', 'dynamited', 'eradicated', 'erased', 'euthanized', 'executed', 'exploded', 'exterminated', 'extirpated', 'felled', 'finished', 'flattened', 'fractured', 'iced', 'killed off', 'knackered', 'knocked off', 'mangled', 'martyred', 'massacred', 'mercy-ruled', 'mowed down', 'murdered', 'mutilated', 'neutralized', 'obliterated', 'offed', 'ousted', 'pulverized', 'put away', 'put down', 'ravaged', 'razed', 'rubbed out', 'ruinated', 'ruined', 'shattered', 'slaughtered', 'smashed', 'smitten', 'snuffed out', 'splintered', 'taken out', 'terminated', 'wasted', 'whacked', 'wiped out', 'wrecked'],
      getModifierSynonym: ['absolutely', 'actually', 'all the way', 'altogether', 'amply', 'assuredly', 'backwards and forwards', 'beyond a shadow of a doubt', 'categorically', 'competently', 'completely', 'comprehensively', 'conclusively', 'de facto', 'decidedly', 'decisively', 'definitely', 'doubtless', 'easily', 'effectively', 'en masse', 'entirely', 'exactly', 'exclusively', 'exhaustively', 'extensively', 'finally', 'for real', 'for sure', 'A to Z', 'from beginning to end', 'fully', 'genuinely', 'hook line and sinker', 'in all', 'in entirety', 'in fact', 'in full', 'point of fact', 'in reality', 'in toto', 'in truth', 'indeed', 'literally', 'no ifs ands or buts', 'on all counts', 'on the button', 'on the money', 'on the nose', 'painstakingly', 'perfectly', 'positively', 'precisely', 'quite', 'really', 'right', 'solidly', 'straight out', 'sure as can be', 'sure as hell', 'sure enough', 'surely', 'thoroughly', 'to the limit', 'to the max', 'to the nth degree', 'totally', 'truly', 'ultimately', 'unabridged', 'unambiguously', 'unanimously', 'unconditionally', 'undividedly', 'unequivocably', 'unquestionably', 'utterly', 'veritably', 'wholly'],
      getHowBadSynonym: ['a betrayal of any expectations', 'a black hole of quality', 'a circus of failure', 'a complete mess', 'a crime against baseball', 'a dumpster fire', 'a garbage-tier record', 'a joke of a thing', 'a kick in the teeth', 'a lesson in how not to do it', 'a letdown, to put it lightly', 'a major fail', 'a mockery of a pro team', 'a nightmare', 'a parody of itself', 'a slap in the face', 'a study in failure', 'a total bust', 'a total dead end', 'a total disaster', 'a total flop', 'a total joke', 'a void of talent', 'all flash, no substance', 'an abomination', 'an absolute blight', 'an absolute trainwreck', 'an epic fail', 'artistic suicide', 'beyond bad', 'beyond saving', 'beyond soul-crushing', 'broken beyond repair', 'can’t be mocked highly enough', 'catastrophically poor', 'complete garbage', 'conceptually bankrupt', 'criminally indefensible', 'critically bad', 'downright nasty', 'flat-out bad', 'functionally useless', 'grade-A crap', 'hot garbage', 'just bollocks', 'just dreadful', 'just plain wrong', 'just toxically bad', 'lacking any redeeming qualities', 'laughably poor', 'like a car crash in slow motion', 'like dragging a corpse', 'like eating glass', 'like nails on a chalkboard', 'like setting money on fire', 'like watching a tragedy unfold every day', 'more than cringe-worthy', 'offensively inept', 'painfully bad', 'permanently off the rails', 'pointless drivel', 'pure crap', 'pure nonsense', 'quality-free', 'really bad', 'reeks of incompetence', 'rock bottom', 'straight-up trash', 'the worst by a mile', 'totally busted', 'totally unacceptable', 'universally reviled', 'utterly awful'],
      getSurprisedSynonym: ['Ain’t that a kick in the head!', 'Ain’t that something!', 'Are you serious?', 'Bazinga!', 'Blimey!', 'Can you believe it?', 'Color me surprised!', 'Damn straight!', 'Fancy that!', 'For real?', 'Gad zooks!', 'Get outta here!', 'Get outta town!', 'Good night, nurse!', 'Gracious sakes!', 'Great balls of fire!', 'Great googly moogly!', 'Great Monfort’s ghost!', 'Great Scott!', 'Heavens above!', 'Heavens to Betsy!', 'Holy crap!', 'Holy guacamole!', 'Holy Moses!', 'Holy smokes!', 'Hot diggity!', 'Huh, how ‘bout that?', 'I’ll be a purple-nosed gopher!', 'Jumpin’ Jackrabbits!', 'Lawdy, lawdy!', 'Lo and behold!', 'Mercy me!', 'Never would’ve guessed!', 'No freaking way!', 'No kidding!', 'No shit!', 'Oh, snap!', 'Old-Timey or Vintage Sayings', 'Pop Culture or Playful Additions', 'Saints alive!', 'Shut the barn door!', 'Shut the front door!', 'Son of a biscuit!', 'Strike me purple!', 'Sweet niblets!', 'That’s bananas!', 'That’s just wild!', 'Wait, what?!', 'Well, butter my biscuit!', 'Well, butter my butt and call me a biscuit!', 'Well, how about that!', 'Well, I never!', 'Well, I’ll be a monkey’s butt.', 'Well, I’ll be a monkey’s uncle.', 'Well, I’ll be a son of a gun.', 'Well, I’ll be a striped possum!', 'Well, I’ll be baked in a pie!', 'Well, I’ll be damned.', 'Well, I’ll be dipped in chocolate!', 'Well, I’ll be dipped in gravy.', 'Well, I’ll be double doggone!', 'Well, I’ll be hog-tied!', 'Well, I’ll be hornswoggled.', 'Well, I’ll be jiggered.', 'Well, I’ll be pickled!', 'Well, I’ll eat my hat!', 'Well, knock me over with a feather!', 'Well, paint me purple and call me a Rockie!', 'What do you know!', 'What in tarnation?!', 'What the heck?!', 'Whoa, dude!', 'Would you look at that!', 'You don’t say!', 'You’re kidding, right?', 'You’ve gotta be shitting me?!'],
      pullItOffSynonym: ['achieve the goal', 'be pitch-perfect', 'be the GOAT', 'beat expectations', 'beat the odds', 'bring it home', 'bring the heat', 'catch on fire', 'close the deal', 'come out ahead', 'come out on top', 'come through', 'come up purple', 'deliver results', 'deliver the goods', 'drive it home', 'execute flawlessly', 'finish first', 'finish strong', 'get it done', 'get over the hump', 'get results', 'get the job done', 'get the win', 'go the distance', 'hit a home run', 'hit it out of the park', 'hit the mark', 'hit the target', 'knock it out of the park', 'land the finish', 'leave us speechless', 'make a breakthrough', 'make it happen', 'make it rain', 'make the cut', 'meet the objective', 'outperform', 'outplay the competition', 'prevail', 'pull a rabbit out of a hat', 'pull it off', 'reach the goal', 'rise above', 'rise to the occasion', 'rock it', 'score a win', 'seal the deal', 'shine bright', 'shine under pressure', 'slay it', 'smash it', 'stick the landing', 'succeed against the odds', 'take it to the next level', 'triumph', 'turn heads', 'walk away a winner', 'win big', 'win out', 'win the day', 'wow the crowd',],
      couldBeWrongSynonym: ['As far as I know.', 'As I currently understand it.', 'Based on what I’ve seen so far.', 'Correct me if I’m wrong.', 'Don’t quote me on this.', 'Feel free to correct me.', 'From my limited experience.', 'From what I understand, that’s not great.', 'I believe so, but I’m not sure.', 'I can’t say for sure.', 'I could always be wrong.', 'I could be mistaken.', 'I could totally have this wrong.', 'I don’t claim to be an expert.', 'I don’t have all the answers.', 'I haven’t looked into this deeply.', 'I haven’t verified this myself.', 'I may be wrong about this.', 'I might be over my head here.', 'I might be talking nonsense.', 'I might not have all the facts.', 'I only have a general understanding.', 'I think that’s right, but I wouldn’t bet on it.', 'I think that’s the case.', 'I wouldn’t call myself an expert.', 'I wouldn’t rely on me for this.', 'I wouldn’t stake my life on it.', 'I’d welcome another opinion on this.', 'I’m all ears if you have a different take.', 'I’m happy to be proven wrong.', 'I’m just sharing what I know.', 'I’m just speculating here.', 'I’m just trying to make sense of it.', 'I’m not 100% sure.', 'I’m not an authority on this.', 'I’m not certain, but...', 'I’m not confident enough to say definitively.', 'I’m not sure how reliable that is.', 'I’m open to being corrected.', 'I’m open to feedback.', 'I’m speaking as a layperson.', 'I’m spitballing here.', 'I’m still learning.', 'I’m still wrapping my head around it.', 'If I’ve misunderstood, please let me know.', 'If that’s not accurate, I’d love to know.', 'It’s a personal perspective.', 'It’s based on what I know, which may be limited.', 'It’s hard to be sure.', 'It’s just a hunch.', 'It’s one interpretation, not the interpretation.', 'It’s possible I misunderstood.', 'Just thinking out loud.', 'Let me know if this doesn’t sound right.', 'Let me know if you see it differently.', 'My grasp on this is pretty basic.', 'My information might be outdated.', 'Off the top of my head.', 'Please chime in if I’ve got that wrong.', 'Seems likely, though I’m not certain.', 'Take this for what it’s worth.', 'Take this with a grain of salt.', 'That appears to be true.', 'That makes sense to me, but I could be off.', 'That’s how I understand it, but I could be wrong.', 'That’s just how I interpret it.', 'That’s just how I see it, but I could be off.', 'That’s just my best guess.', 'That’s just one way to look at it.', 'That’s what I recall, but my memory might be off.', 'That’s what I’ve gathered so far.', 'That’s just like, my opinion, man.', 'There may be other factors at play.', 'There’s a good chance I missed something.', 'There’s always a chance I’m missing something.', 'Things could have changed.', 'I could be incorrect.', 'This is just a rough idea.', 'This is just my perspective.', 'This is just my take.', 'This is more opinion than fact, but it might be a fact.', 'But you don’t have to take my word for it.'],
      workOnTheirGolfSwingSynonym: ['brew their own beer', 'build a birdhouse', 'do indoor gardening', 'do some wood carving', 'explore some hiking trails', 'go alpine skiing', 'go birdwatching', 'go bowling', 'go cross-country skiing', 'go downhill skiing', 'go for a bike ride', 'go for a hike', 'go snowshoeing', 'knit a scarf', 'learn origami', 'make a scrapbook', 'make a vision board', 'make their own candles', 'meditate in silence', 'play basketball', 'play board games', 'play video games', 'practice yoga', 'rewatch their favorite shows', 'start a blog', 'take a bubble bath', 'take a cooking class', 'take a dance class', 'take a pottery class', 'take a scenic train ride', 'take photos at the park', 'tend their garden', 'visit a botanical garden', 'visit a farmer’s market', 'visit a museum', 'watch classic films', 'watch nature cams', 'watch stand-up comedy', 'watch the sunset', 'work on their golf swing', 'write poetry'],
      oldNewsSynonym: ['a recycled talking point', 'a ship that has sailed', 'a tale as old as time', 'a tired point', 'already been addressed', 'ancient history', 'known to all', 'more of the same', 'much ado about nothing', 'no surprise here', 'not exactly groundbreaking', 'not front-page material', 'nothing new under the sun', 'nothing novel', 'old hat', 'old news', 'on repeat', 'par for the course', 'part of the status quo', 'rinse and repeat', 'same team and same script', 'so predictable', 'stale as old bread', 'the same old song', 'the same old story', 'the usual drill', 'water under the bridge', 'worn and weary', 'yawn-worthy', 'yesterday’s news'],
      imSkepticalSynonym: ['Color me unconvinced.', 'I have my doubts.', 'I need more proof.', 'I remain analytically cautious.', 'I remain intellectually hesitant.', 'I require more convincing data.', 'I won’t assume anything.', 'I won’t jump to conclusions.', 'I’ll approach that with a critical eye.', 'I’ll be cautious in interpreting that.', 'I’ll be watching closely.', 'I’ll consider it, but with reservations.', 'I’ll keep questioning it.', 'I’ll maintain my doubts.', 'I’ll remain cautious.', 'I’ll remain impartial for now.', 'I’ll remain observant.', 'I’ll remain unconvinced for now.', 'I’ll stay doubtful.', 'I’ll stay logically detached.', 'I’ll treat that claim carefully.', 'I’ll treat that claim skeptically.', 'I’ll wait for more evidence.', 'I’ll wait for peer review.', 'I’ll wait for the receipts.', 'I’ll wait to be convinced.', 'I’m approaching this with caution.', 'I’m critically evaluating the situation.', 'I’m hesitant to embrace that.', 'I’m holding back belief.', 'I’m inclined to question that.', 'I’m keeping a rational distance.', 'I’m keeping an emotional distance.', 'I’m keeping an open but critical mind.', 'I’m keeping my expectations low.', 'I’m keeping one eyebrow raised.', 'I’m not buying it yet.', 'I’m not convinced.', 'I’m not easily persuaded.', 'I’m not falling for that.', 'I’m not fully aligned with that yet.', 'I’m not ready to endorse it.', 'I’m not taking that at face value.', 'I’m not taking the bait.', 'I’m not taking this lightly.', 'I’m questioning the assumptions.', 'I’m reserving judgment.', 'I’m skeptical until proven otherwise.', 'I’m staying on the fence.', 'I’m still forming my opinion.', 'I’m still not sure.', 'I’m treading carefully here.', 'I’m viewing this development with some reservation.', 'I’m wary of confirmation bias.', 'I’m withholding belief.', 'I’ve heard that one before.', 'Let’s keep this under review.', 'Let’s not drink the Rockies Are Good Kool-Aid just yet.', 'Let’s not get ahead of ourselves.', 'Let’s see how it unfolds.', 'Let’s take a wait-and-see approach.', 'Not jumping on that bandwagon.', 'Sounds rocky to me.', 'That’s a tentative maybe.', 'The conclusion seems premature.', 'Yeah, I’m not sold.', 'Yeah, I’m skeptical.'],
      betterThanExpectedSynonym: ['a bit better than expected', 'a notch above average', 'a slight improvement', 'better than i thought they would be', 'better than nothing', 'chugging along', 'consistent, if unremarkable', 'delivering acceptable results', 'delivering mild gains', 'demonstrating minor improvement', 'doing a bit better than usual', 'doing alright', 'doing fine', 'doing okay-ish', 'earning slightly higher marks', 'exceeding targets by a small margin', 'getting by just fine', 'getting the essentials done', 'going better than it looks', 'going okay', 'going reasonably well', 'going smoother than i figured', 'hanging in there', 'having no complaints so far', 'having no major setbacks', 'having progress that is modest but real', 'having small wins here and there', 'hitting the mark and then some', 'holding together', 'holding up well', 'just above the benchmark', 'just doing their thing', 'keeping pace', 'keeping things afloat', 'making it work', 'marginally outperforming', 'meeting and occasionally exceeding goals', 'meeting baseline goals', 'modestly on track', 'modestly successful', 'more or less on track', 'not bad—actually kind of good', 'not great, not terrible', 'nothing extraordinary, but solid', 'nothing fancy, just steady', 'nothing special, but it’s working', 'on a decent path', 'on the better side of average', 'performing reliably', 'performing slightly above average', 'quietly making moves', 'quietly outperforming', 'showing signs of growth', 'showing signs of strength', 'slightly ahead of projections', 'so-so, but functional', 'somewhat ahead of the curve', 'staying consistent', 'steady but unspectacular', 'subtly getting better', 'surpassing expectations', 'surpassing minimum standards', 'surpassing minimum standards', 'surprisingly steady', 'surprisingly steady', 'ticking the boxes', 'turning out alright', 'under control', 'within acceptable range', 'working out better than planned', 'working out okay', 'working out okay'],
      areKillingItSynonym: ['are absolutely mind-blowing', 'are absolutely remarkable', 'are absolutely unreal', 'are astonishing me', 'are bending my mental space', 'are bending the boundaries of my mind', 'are beyond anything i imagined', 'are beyond impressive', 'are beyond words', 'are blowing me away', 'are blowing the ceiling off', 'are breaking my brain', 'are captivating my attention', 'are challenging my assumptions', 'are completely rocking my world', 'are cooking fr', 'are cracking open my brain', 'are dancing on my neurons', 'are doing numbers', 'are eating this up', 'are exceeding every expectation', 'are exceeding what i thought was possible', 'are expanding my thinking', 'are expanding the universe inside my head', 'are flipping my brain inside out', 'are freaking me out (in awe)', 'are giving me chills', 'are giving me life', 'are glitching my brain', 'are going hard', 'are hitting different', 'are killing it', 'are knocking my socks off', 'are leaving me speechless', 'are lighting up my brain', 'are like magic unfolding', 'are like poetry in motion inside my head', 'are like seeing the color purple for the first time', 'are low-key frying my brain', 'are making a powerful impact', 'are making me lose it', 'are making me question reality', 'are making my head spin', 'are making my inner child cheer', 'are making my jaw drop', 'are making my neurons dance', 'are melting my brain', 'are messing me up (in the best way)', 'are messing with my head (in a good way)', 'are on another level', 'are opening my eyes', 'are painting new realities for me', 'are profoundly impressive', 'are proving to be revolutionary', 'are pure sorcery', 'are pushing my limits of understanding', 'are putting my brain in overdrive', 'are redefining brilliance', 'are reshaping my perspective', 'are rewriting my mental software', 'are rewriting what i thought i knew', 'are sending me', 'are seriously impressing me', 'are setting new standards', 'are shifting my entire outlook', 'are sparking new worlds in my mind', 'are spinning my mind like a carousel', 'are straight fire 🔥', 'are stretching the edges of what i understand', 'are stunning me', 'are teleporting me to another dimension', 'are throwing me for a loop', 'are tickling my brain in all the right ways', 'are too much (in a good way)', 'are totally amazing me', 'are totally wowing me', 'are turning my thoughts into confetti', 'are turning thought into wonder', 'are twisting my noodle', 'are unraveling my reality', 'are waking my soul'],
      inShockWinningSynonym: ['Absolute chaos.', 'Are you fucking serious?.', 'Are you kidding me?!', 'Beyond comprehension.', 'Brain = fried.', 'Bruh...', 'For the love of all that is holy.', 'Well, fuck me sideways.', 'Full meltdown mode.', 'Get the fuck out of here.', 'Good lord.', 'Holy banana pants.', 'Holy cow.', 'Holy ever-loving shit.', 'Holy fuck.', 'Holy moly.', 'Holy mother of God.', 'Holy shitballs.', 'Holy smokes.', 'Hot damn.', 'I can’t even.', 'I can’t fucking believe this.', 'I can’t function.', 'I did NOT see that coming.', 'I need a minute.', 'I need to lie down.', 'I’m absolutely shook.', 'I’m deceased.', 'I’m freaking out.', 'I’m gonna pass out.', 'I’m levitating.', 'I’m losing it.', 'I’m losing my damn mind.', 'I’m shook.', 'Jesus fucking Christ.', 'Jesus tap-dancing Christ.', 'Literal chaos.', 'Main character energy.', 'Maximum overload.', 'Mother of all things.', 'My brain just short-circuited.', 'My eyeballs are sweating.', 'My mind = blown.', 'No freaking way.', 'No fucking way.', 'Oh my fucking god.', 'Oh my god.', 'Oh my stars.', 'OH. MY. GOD.', 'Peak madness.', 'Say what now?!', 'Send help.', 'Shit just got real.', 'Someone hold me.', 'Sweet baby Jesus.', 'Sweet merciful crap.', 'Take all my money.', 'That escalated quickly.', 'That hit me like a truck.', 'That just blew my mind.', 'That just happened?!', 'That sent me.', 'That’s absurd.', 'That’s cosmic.', 'That’s cracked.', 'That’s fucking wild.', 'This ain’t real.', 'This broke my soul.', 'This can’t be happening.', 'This changes everything.', 'This is batshit crazy.', 'This is carnage.', 'This is fucking insane.', 'This is insanity.', 'This is off the rails.', 'This is unreal.', 'Total madness.', 'Utter destruction.', 'Well I’ll be damned.', 'Holy shit on a stick.', 'What a fucking riot.', 'What an explosion of not-sucking.', 'What in the name of Zeus’s beard.', 'What in the world?!', 'What is this sorcery?!', 'What just happened?!', 'What kind of magic is this?!', 'What on earth?!', 'What sorcery is this?!', 'What the actual fuck.', 'What the flying fuck.', 'What the fuck is happening?!', 'What the hell?', 'Who ordered the chaos?!', 'WTF.', 'You’ve got to be fucking kidding me!'],
      delaySynonym: ['argue with fate', 'avoid the conclusion', 'cling to false hope', 'defer the endgame', 'delay destiny', 'delay saying goodbye to this game', 'delay the collapse', 'delay the defeat', 'delay the downfall', 'delay the funeral', 'delay the inevitable', 'delay the landslide', 'delay the outcome', 'delay the verdict', 'drag out the decision', 'extend the suffering', 'extend the timeline', 'extend the tragedy', 'fight gravity', 'forestall the outcome', 'hold off the heartbreak', 'hold off the unavoidable', 'keep death waiting', 'kick the can down the road', 'pause the process', 'postpone fate', 'postpone the decline', 'postpone the doom', 'postpone the unavoidable', 'prolong the agony', 'prolong the conclusion', 'prolong the pain', 'push back the deliverable', 'push back the end', 'push back the fall of night', 'push the deadline', 'put a band-aid on a bullet wound', 'put off the end', 'put off the reckoning', 'stall the execution', 'stall the inevitable', 'stretch out the ending'],
      goingToHurtSynonym: ['good luck walking that one off', 'oof, preemptive ouch', 'that might break something', 'that move’s going to sting', 'that won’t be pretty', 'that’ll be a blow to the team', 'that’ll be a hard lesson learned', 'that’ll be a tough pill to swallow', 'that’ll be felt for days', 'that’ll be fun not', 'that’ll be hard to recover from', 'that’ll be sore in the morning', 'that’ll bruise for sure', 'that’ll derail our plans', 'that’ll disrupt everything', 'that’ll have a price', 'that’ll have consequences', 'that’ll leave a crater', 'that’ll leave a mark', 'that’ll linger emotionally', 'that’ll ruin our day', 'that’ll ruin our vibe', 'that’ll send shockwaves', 'that’ll sting emotionally', 'that’ll take a toll', 'that’ll throw a wrench in it', 'that’ll wound our pride', 'that’ll wreck the momentum', 'that’s a bad idea waiting to happen', 'that’s a mistake in the making', 'that’s a punch to the gut', 'that’s a recipe for disaster', 'that’s a trainwreck incoming', 'that’s going to be a heavy blow', 'that’s going to be a mess', 'that’s going to be awkward', 'that’s going to be devastating', 'that’s going to be painful', 'that’s going to break something', 'that’s going to burn', 'that’s going to burn bridges', 'that’s going to cause a storm', 'that’s going to cause some damage', 'that’s going to cause trouble', 'that’s going to crack our confidence', 'that’s going to cut deep', 'that’s going to explode in our face', 'that’s going to hit hard', 'that’s going to hurt our chances', 'that’s going to hurt our feelings', 'that’s going to knock the wind out', 'that’s going to leave emotional scars', 'that’s going to mess us up', 'that’s going to open up wounds', 'that’s going to ruin our weekend', 'that’s going to shake our core', 'that’s going to shatter us', 'that’s going to smart', 'that’s going to sting', 'that’s going to sting the ego', 'that’s going to suck shit', 'that’s going to take some therapy', 'that’s going to wreck us', 'that’s gonna hurt', 'that’s gonna leave a dent', 'that’s gonna need stitches', 'that’s gonna rattle the bones', 'that’s how bad days are made', 'that’s not going to end well', 'that’s not going to feel good', 'that’s not going to go over well', 'that’s not going to heal quickly', 'well, that’s going to suck'],
      youNeverKnowSynonym: ['a bit of luck could turn the tide', 'all bets aren’t off yet', 'anything’s possible', 'can’t hurt to try', 'could be a fluke—but in our favor', 'could be a lucky roll', 'could be a not-losing hand', 'could be a turning tide', 'could be our lucky break', 'could be our lucky moment', 'could be the break we need', 'could go either way', 'could go our way', 'fingers crossed', 'here’s hoping', 'high risk, high reward', 'if we’re lucky, this could be ok', 'it could work out in our favor', 'it might just be our time', 'it might just work out', 'it’s a long shot, but maybe', 'it’s a toss-up', 'it’s in the realm of possibility', 'it’s not a sure loss, so we’ve got a shot', 'it’s worth a shot', 'just maybe, things will break our way', 'let’s hope for the best', 'let’s roll the dice', 'let’s take a chance', 'let’s take a stab at it', 'let’s try and see what happens', 'luck might be on our side', 'luck might smile on us', 'maybe fortune will favor us', 'maybe it’ll go ok', 'maybe it’s our lucky match', 'maybe the cards fall our way', 'maybe the odds are in our favor', 'maybe the tide is turning', 'maybe the universe is on our side', 'maybe things will swing our way', 'our luck could change', 'something lucky might come our way', 'stranger things have happened', 'the stars might align', 'the wheel might spin our way', 'there’s a chance things go our way', 'there’s a non-zero chance', 'there’s always a possibility', 'there’s always a tiny bit of hope', 'things might fall into place', 'we could end up not losing this', 'we could get a break', 'we could luck into not losing', 'we might beat the odds', 'we might catch a lucky break', 'we might just catch a break', 'we might ride a lucky streak', 'we’ll give it a go—might get lucky', 'we’ll see what happens', 'we’re due for something good', 'we’re not out of the running', 'we’re overdue for something lucky', 'we’ve got a chance, however small', 'we’ve got a sliver of a chance', 'we’ve still got a shot', 'who knows?', 'you never know', 'you never know till you try'],      
      getGameUpdatesSynonym: ['access all Rockies game reports.', 'be a Did The Rockies Lose insider. 👀', 'be notified of Rockies updates.', 'be part of the Rockies fan network.', 'be part of the Rockies not-best season.', 'be the first to know when the Rockies are losing.', 'be there for every Rockies run allowed.', 'be updated on Rockies results.', 'be updated on Rockies standings and more.', 'catch every Rockies update.', 'catch Rockies games live right here.', 'don’t miss a Rockies moment.', 'follow all the Rockies action, for better or worse.', 'follow the Rockies lead changes in real time.', 'follow the Rockies’ less-than-stellar journey.', 'get automatic push updates for Rockies basebal.', 'get automatic push updates for the Rockies.', 'get live Rockies updates.', 'get notified about every Rockies game and more.', 'get Rockies game news and standings.', 'join the Rockies conversation. It’s quite a conversation.', 'keep current on Rockies games.', 'keep track of Rockies scores and more.', 'keep up with the Rockies.', 'know every one of our wild stats.', 'know how uh, well, the Rockies are doing.', 'know what’s happening with the Rockies.', 'learn what’s happening with the Rockies.', 'listen to Rockies game coverage.', 'monitor the Rockies game live.', 'never miss a Rockies score.', 'receive Rockies news and updates.', 'receive Rockies scores by notification.', 'ride with the Rockies all season.', 'see how the Rockies, uh, perform.', 'stay close to the Rockies.', 'stay connected with Rockies Nation. We’re all in this together.', 'stay hyped on Rockies games.', 'stay in the loop with Rockies games.', 'stay informed on Rockies "performance."', 'stay informed on Rockies matchups and results.', 'stay on top of the Rockies scores.', 'stay sharp on Rockies scores.', 'stay tuned to Rockies baseball.', 'stay up to date on Rockies games.', 'stream Rockies game updates.', 'subscribe to Rockies coverage.', 'subscribe to Rockies updates.', 'track every Rockies matchup.', 'tune in for Rockies updates.', 'understand the Rockies’ "momentum."', 'view Rockies highlights post-game.', 'watch the Rockies "performance" closely.', 'watch the Rockies season "unfold."'],
      followRockiesFeed: ['be active in the Rockies fan scene', 'be informed about Rockies players and games', 'be on top of Rockies headlines', 'be part of the Rockies community', 'catch Rockies post-game analysis', 'catch Rockies vibes, for better or worse', 'celebrate Rockies not-losses online', 'chat with other Rockies fans', 'check for Rockies updates', 'cheer the Rockies on with the crowd', 'connect with Rockies Nation', 'engage in Rockies-related discussions', 'engage with the Rockies community', 'follow official Rockies announcements', 'follow Rockies fan chatter', 'follow Rockies media coverage and games', 'follow Rockies news outlets and more', 'follow the Rockies "journey" online', 'get all the Rockies tea', 'get insight into Rockies’ moves and more', 'get involved in Rockies conversations', 'get real-time Rockies news', 'get Rockies organizational updates', 'get the latest on the Rockies', 'join in on Rockies traditions and talk about tacos', 'join the conversation about the Rockies', 'keep current with Rockies reporting and gossip', 'keep informed about Rockies trends', 'keep tabs on every Rockies’ development', 'keep up with Rockies headlines', 'keep up with the Rockies scene', 'know what’s going on with the Rockies', 'know what’s up in Rockies world', 'know who’s hot (and not) on the Rockies', 'learn what’s new in Rockies world', 'listen to the Rockies fan perspective', 'post and read all of your Rockies opinions', 'react to Rockies games, for better or worse', 'read everyone’s hot takes on Rockies news', 'read Rockies insider reports and more', 'ride the Rockies wave (I’m not saying it’s a good wave)', 'see what fans at Coors Field are up to and more', 'see what’s new with the Rockies', 'share your pics and videos from Coors Field and more', 'stay aware of Rockies trade news', 'stay in the Rockies loop', 'stay informed about the Rockies', 'stay up to date on Rockies news', 'stay updated on Rockies stats and stories', 'stay updated on the Rockies "performance"', 'track the latest Rockies updates', 'track the latest Rockies updates', 'tune into Rockies talk', 'tune into Rockies talk online', 'view Rockies news roundups and more', 'view Rockies news roundups and more', 'watch Rockies news roll in, for better or worse'],
      holdOntoYourButtsSynonym: ['And now… chaos!', 'Brace yourself.', 'Buckle up.', 'Can’t wait to explain this later.', 'Cue the chaos.', 'Damage control won’t help this.', 'Get ready for a meltdown.', 'Grab your emotional support beverage.', 'Hands up or hang on?', 'Hang on tight.', 'Here comes the chaos.', 'Here comes the nonsense.', 'Here we go again.', 'Hold onto your tacos.', 'Hope you wore your brown pants.', 'Hope you’re ready for this.', 'I don’t like where this is going.', 'I’ve got a bad feeling about this.', 'It’s all downhill from here.', 'It’s unraveling fast.', 'Light the match, watch it burn.', 'Mark my words, this’ll get ugly.', 'May God have mercy on our souls.', 'Mind the whiplash.', 'Not exactly smooth sailing.', 'Oh boy, here we go.', 'Panic quietly!', 'Prepare to question your life choices.', 'Recalibrating expectations.', 'Ruh-roh.', 'Set phasers to “oh no.”', 'Something’s definitely off.', 'That can’t be good.', 'That escalated quickly — and it’s not over.', 'That escalated quickly.', 'That might trigger something bigger.', 'That’s a landmine waiting to go off.', 'That’s a powder keg.', 'That’s not a good sign.', 'That’s not ideal.', 'The situation is deteriorating.', 'The storm is coming.', 'The wheels just came off.', 'There are red flags all over this.', 'Things are about to get messy.', 'Things are about to get spicy.', 'Things are going off the rails… expectedly.', 'This could be bad.', 'This could spiral quickly.', 'This has danger written all over it.', 'This is going sideways real fast.', 'This is gonna be a bumpy ride.', 'This ride has no brakes.', 'This won’t end well.', 'Time to open the chaos portal.', 'Trouble is just getting started.', 'Trouble’s brewing.', 'Unstable variables incoming.', 'We may have a situation.', 'We’re entering risky territory.', 'We’re gonna need a bigger lifeboat.', 'We’re in the danger zone.', 'We’re playing with fire now.', 'What could go wrong?', 'What could possibly go wrong?',],
      didntGoGreatSynonym: ['A beautiful disaster.', 'A bit of a dumpster fire.', 'A bit of a hiccup.', 'Could’ve been smoother.', 'Could’ve gone better.', 'Didn’t exactly shine.', 'Didn’t go to plan.', 'Didn’t quite achieve the goal.', 'Didn’t stick the landing.', 'Far from perfect.', 'Like a balloon losing air.', 'Like watching a slow-motion crash.', 'Not a success.', 'Not great, Bob.', 'Not how I imagined it.', 'Not our best moment.', 'Not our finest hour.', 'Oh, it was fantastic (not).', 'Results were suboptimal.', 'Results weren’t promising.', 'Slightly off-course.', 'That was a bust.', 'That wasn’t ideal.', 'That went well... if you’re into failure.', 'The execution was flawed.', 'The outcome was disappointing.', 'The wheels came off.', 'There were several issues.', 'There were some setbacks.', 'Things didn’t quite work out.', 'Things unraveled.', 'Things went south.', 'Total buzzkill.', 'We didn’t land well.', 'We encountered difficulties.', 'We fell a little flat.', 'We fell short.', 'We got derailed.', 'We had a learning experience.', 'We had a setback.', 'We had a struggle.', 'We had some challenges.', 'We hit a few bumps.', 'We hit some snags.', 'We kind of sucked.', 'We kind of tanked.', 'We kinda blew it.', 'We kinda whiffed it.', 'We left room for improvement.', 'We missed expectations.', 'We missed the mark.', 'We missed the target.', 'We sank like a stone.', 'We underdelivered.', 'We underperformed.', 'We was a bit of a fail.', 'We went a bit to crap.', 'We went downhill.', 'We went off the rails.', 'We went poorly.', 'We went sideways.', 'We went up in flames a bit.', 'We were a bit lacking.', 'We were a bit of a mess.', 'We were a bit of a trainwreck.', 'We were a bit off.', 'We were a bit rough.', 'We were less than stellar.', 'We were rough, man.', 'We weren’t entirely successful.', 'We weren’t pretty.',],
     wentOkSynonym: ['A functioning mess of baseball play.', 'A modest success.', 'A small victory.', 'Bare minimum met.', 'Better than nothing.', 'Could’ve been worse.', 'Execution was solid.', 'I guess that counts as a plus.', 'I think it was a mild success.', 'I think we did all right for ourselves.', 'I think we did pretty well.', 'I think we held our own.', 'I wouldn’t call it a failure.', 'I’d say it went okay.', 'I’ll count it as a W.', 'I’ll take it.', 'I’m not complaining.', 'I’m satisfied enough.', 'Just better than mediocre.', 'Let’s call it a success and move on.', 'Let’s just say it was fine.', 'No major complaints.', 'Nobody cried, so that’s a win.', 'Not bad at all.', 'Not too bad.', 'Nothing to write home about, but fine.', 'Results aligned with the goals.', 'That was a decent effort.', 'That went smoother than expected.', 'That worked out okay.', 'That’ll do.', 'That’ll work.', 'The end result was respectable.', 'The outcome was fair-to-middlin’.', 'We achieved satisfactory results.', 'We avoided disaster.', 'We checked all the boxes.', 'We delivered a solid effort.', 'We delivered.', 'We did acceptably.', 'We did fine.', 'We did reasonably well.', 'We did the job.', 'We did what we came to do, except not as bad.', 'We did what we could.', 'We didn’t bomb.', 'We didn’t completely flop.', 'We didn’t fall apart.', 'We didn’t screw it up!', 'We didn’t tank.', 'We faked it well enough.', 'We got it done.', 'We got through it.', 'We had a competent showing.', 'We handled it.', 'We held steady.', 'We kept it together.', 'We kept things steady.', 'We looked intentional, mostly.', 'We looked okay from a distance.', 'We made it through.', 'We made it work.', 'We maintained course.', 'We managed okay.', 'We met expectations.', 'We met our baseline.', 'We met the minimum.', 'We passed the bar.', 'We performed adequately.', 'We played out okay.', 'We produced consistent results.', 'We pulled it off.', 'We squeaked by.', 'We stayed afloat.', 'We survived.', 'We turned out alright.', 'We was a “good enough” kind of deal.', 'We went alright.', 'We went better than I thought.', 'We were better than expectations.', 'We were decent.', 'We were okay-ish.', 'We were passable.', 'We were within the success range.', 'We weren’t terrible.', 'We worked out, more or less.',],      
     sellTheTeamSynonym: ['Bill Schmidt continues as GM of the Rockies.', 'Bill Schmidt is still the Rockies’ general manager.', 'Bill Schmidt remains the Rockies’ GM.', 'Don’t worry—nothing’s changed with the Rockies GM. Still Schmidt.', 'No change at Rockies GM—still Schmidt.', 'No changes in the Monfort family dynasty so far.', 'No developments in the sale of the team yet.', 'No long-lost Monfort has stepped in to save Rockies’ season.', 'No new Monfort heir has emerged from the shadows to run the team.', 'No relief yet—the Monforts haven’t sold.', 'No sale from the Monforts has occurred.', 'No, the Monforts have not found a new brother to start running the team.', 'No, the Rockies haven’t fired Schmidt.', 'Nope, still no fresh Monfort to hand the keys to.', 'Nothing has moved on the team ownership front.', 'Nothing’s changed—Monforts still own the Rockies.', 'Rockies GM Bill Schmidt has not been replaced.', 'Rockies GM Bill Schmidt’s still calling the shots.', 'Sadly, no mystery Monfort has been appointed GM yet.', 'Sadly, the Monforts still own the team.', 'Same story: Monforts still own the team.', 'Shockingly, the Monforts still haven’t sold.', 'Somehow, Bill Schmidt is still the GM.', 'Still no new, different Monfort brother to take the wheel.', 'Still no word on a team sale.', 'Still waiting on that sale of the team.', 'Team ownership remains with the Monforts.', 'Team sale talks (if any) haven’t materialized.', 'The Bill Schmidt era continues (for some reason).', 'The Monfort family tree hasn’t sprouted a savior.', 'The Monfort succession plan remains mysteriously empty.', 'The Monforts are holding on—for now.', 'The Monforts are still clinging to the team.', 'The Monforts continue to hold on to the team.', 'The Monforts have retained control of the team.', 'The Monforts haven’t let go of the team.', 'The Monforts haven’t parted with the team.', 'The Monforts haven’t promoted another relative—yet.', 'The Monforts remain the team’s owners.', 'The Monforts still own the team.', 'The Monforts still own the team.', 'The ownership situation hasn’t changed.', 'The Rockies are still led by GM Bill Schmidt.', 'The Rockies haven’t replaced Bill Schmidt as GM.', 'The sale hasn’t happened.', 'The team hasn’t been sold by the Monforts.', 'The team hasn’t changed hands.', 'The team is still in the Monforts’ hands.', 'The team is still under Monfort ownership.', 'The team is yet to be sold.', 'The team remains firmly in the usual Monfort hands.', 'The team remains unsold.', 'The team still in the same hands.', 'There has been no change in team ownership.', 'There’s been no transfer of team ownership.', 'They haven’t sold it yet.', 'Unfortunately, the Monforts are still in charge.', 'Unfortunately, the Monforts remain in charge.', 'We’re still stuck with the Monforts.'],      
     newsAlertSynonym: ['Alert', 'Breaking', 'Developing Now', 'Exclusive', 'Flash Report', 'Fresh Off the Press', 'Heads Up', 'Insider Info', 'Late-Breaking News', 'Latest Update', 'Leaked Details', 'Live Update', 'News Details', 'New Development', 'News Update', 'Ongoing Coverage', 'Quick Update', 'Real-Time Report', 'Scoop', 'Situation Update', 'Update', 'You Heard It Here First',], 
     inARoughSpotSynonym: ['It’s a bit of a sh*tshow, honestly.', 'It’s a bit shaky at the moment.', 'It’s a high-stress period for us.', 'It’s been a bumpy ride.', 'It’s been a rough ride.', 'It’s been a rough season.', 'It’s been a tough stretch.', 'It’s been emotionally exhausting.', 'It’s rough out here.', 'There’s a lot going on around here.', 'Things are a bit messy.', 'Things are just... off.', 'Things are a bit weird right now.', 'Things are less than ideal.', 'Things are rough right now.', 'Things are tough, but we’re pushing through.', 'Things aren’t great right now.', 'Things aren’t running smoothly.', 'Things have been a little challenging.', 'This is taking a toll on us.', 'This season is hitting a few bumps.', 'We’re a bit off course.', 'We’re a bit off our game.', 'We’re a bit off track.', 'We’re barely holding it together.', 'We’re dealing with some issues.', 'We’re down, but not out.', 'We’re emotionally drained.', 'We’re facing a bit of challenges.', 'We’re facing some challenges.', 'We’re facing some complications.', 'We’re facing some setbacks.', 'We’re feeling overwhelmed.', 'We’re feeling the weight of it.', 'We’re going through a low point.', 'We’re going through an adjustment.', 'We’re going through a tough time.', 'We’re hurting, to be honest.', 'We’re in a bit of a funk.', 'We’re in a bit of a jam.', 'We’re in a rough spot at the moment.', 'We’re in deep right now.', 'We’re in stormy waters.', 'We’re in survival mode.', 'We’re in the eye of the storm.', 'We’re in transition.', 'We’re in a rough patch, is all.', 'We’re managing some difficulties.', 'We’re navigating a difficult time.', 'We’re not in the best shape.', 'We’re not meeting expectations.', 'We’re not where we want to be.', 'We’re stretched pretty thin.', 'We’re struggling a bit.', 'We’re struggling, but not stopping.', 'We’re a bit strained right now.', 'We’ve been in a rough patch.', 'We’ve hit a few snags.', 'We’ve hit some turbulence.', 'We’ve seen better days.',], 
     inAMiddleSpotSynonym: ['Could be worse, could be better.', 'Eh, it’s fine. I guess.', 'I don’t hate it, but I don’t love it.', 'No strong feelings either way.', 'Not good, but not bad either.', 'Not mad, not happy, just... here.', 'It is what it is.', 'It’s a coin flip every night.', 'It’s a mixed bag out there.', 'It’s aggressively mediocre.', 'It’s giving “meh.”', 'It’s hovering around average.', 'It’s just kind of... there.', 'Not exciting, but not a disaster.', 'It’s okay. Not great, not terrible.', 'It’s the definition of mid.', 'Look, we’re surviving.', 'Mid is the vibe right now.', 'Neither here nor there, honestly.', 'Not worth celebrating, not worth panicking.', 'Not terrible, not great.', 'Nothing to write home about.', 'Right in the thick of mediocrity.', 'Solidly in no man’s land.', 'Some days are up, some days are down.', 'Somewhere between “fine” and “I guess.”', 'Stuck in neutral.', 'The vibes are... neutral.', 'There are good days and bad days.', 'There’s some good, there’s some bad.', 'Things are happening. Some are okay.', 'Things are just sort of... happening.', 'Things are neither great nor awful.', 'Things are steady. Just steady.', 'Treading water, basically.', 'We exist in the middle of the standings.', 'We’re coasting along.', 'We’re floating somewhere in the middle.', 'We’re holding steady, for now.', 'We’re hovering around .500 energy.', 'We’re in a “let’s see” kind of spot.', 'We’re in the gray zone.', 'We’re in the land of “could go either way.”', 'We’re just kind of vibing in the middle.', 'We’re managing. That’s about it.', 'Not bad enough to tank, not good enough to dream.', 'Not great, but not embarrassing.', 'We’re right in the middle of the pack.', 'Somewhere between hope and disappointment.', 'Splitting the difference between good and bad.', 'We’re treading water.', 'We’ve been inconsistent, to put it mildly.', 'Could be worse. Could also be much better.',], 
     inAGoodSpotSynonym: ['Actually looking pretty decent, knock on wood.', 'Am I allowed to be optimistic? Asking for me.', 'Color me cautiously impressed.', 'Dare I say... things are going well?', 'Don’t jinx it, but things are looking up.', 'Don’t look now, but we might actually be good.', 'Don’t tell anyone, but I’m starting to believe.', 'Excuse me while I cautiously celebrate.', 'Hold on, are we... good?', 'I don’t want to get my hopes up, but here I am.', 'I don’t want to jinx it.', 'I mean, I’m not saying it’s sustainable, but wow.', 'I might be smiling. Don’t read into it.', 'I won’t say we’re great, but we’re looking sharp.', 'I’ll believe it when I see a full season of it.', 'I’m cautiously optimistic. Emphasis on cautiously.', 'Enjoying this, but waiting for the other shoe to drop.', 'Not excited yet. Okay, maybe a little.', 'I’m suspicious but impressed.', 'I’m trying not to jinx it, but this is fun.', 'Is this... hope? It feels weird.', 'It’s early, but the vibes are immaculate.', 'It’s going well. Suspiciously well.', 'Let me enjoy this before something goes wrong.', 'Listen, I’ve been hurt before, but this feels real.', 'Not saying World Series, but not not saying it.', 'Okay, this is actually going well.', 'Okay, we might be cooking.', 'Pinch me, because this is going well.', 'Quietly optimistic over here.', 'Shh, don’t spook it.', 'So far so good, but I’ve been burned before.', 'Something good is happening and I’m terrified.', 'Tell me I’m not dreaming.', 'The results are... actually kind of great?', 'The vibes are cautiously elite.', 'Things are clicking. Scared to say it out loud.', 'Things are going well, which makes me nervous.', 'Things are looking up. Trying not to overthink it.', 'This feels good. Too good. What’s the catch?', 'This is the best we’ve looked in a while, honestly.', 'This is what hope feels like, right?', 'Wait, are we actually having fun this season?', 'We might actually have something here.', 'We’re cooking. Keeping expectations in check.', 'We’re doing things. Good things. It’s confusing.', 'We’re in a good spot. Don’t tell the universe.', 'We’re looking solid, and I’m cautiously here for it.', 'We’re not just surviving’we’re competing.', 'Playing well, and I’m afraid to say it.', 'Riding high, but let’s not get ahead of ourselves.', 'Got some momentum. Cautiously thrilled.', 'Well, this is a pleasant surprise.',], 
     anythingCouldHappenNextSynonym: ['Anything could happen next.', 'Beats me what happens next.', 'Everything beyond this is a question mark.', 'I can’t say what comes after this.', 'I can’t see the next step.', 'I didn’t plan this far.', 'I don’t know what’s going to happen.', 'I have no clue what’s coming next.', 'I have no idea where this is going.', 'I haven’t the faintest idea what’s next.', 'I honestly can’t predict what’s next.', 'I wish I knew what will happen, but I really don’t.', 'I’m at a loss about what follows next.', 'I’m clueless about what happens next.', 'I’m completely in the dark about what’s next.', 'I’m flying blind from here.', 'I’m in over my head now.', 'I’m just along for the ride now.', 'I’m just going with the flow now.', 'I’m just here for the chaos.', 'I’m just letting it play out.', 'I’m just riding the wave.', 'I’m just watching this unfold.', 'I’m just winging it from here.', 'I’m lost from here on out.', 'I’m navigating without a map.', 'I’m not sure how this plays out.', 'I’m not sure where this is headed.', 'I’m open to whatever comes next.', 'I’m totally unsure of what happens now.', 'I’m waiting to see what fate decides.', 'I’m winging it from here.', 'I’ve got no say in what’s next.', 'I’ve handed it over to fate.', 'I’ve hit the edge of certainty.', 'I’ve officially run out of predictions.', 'I’ve reached the limit of what I know.', 'I’ve surrendered to the unknown.', 'It could go anywhere from here.', 'It’s a complete unknown.', 'It’s a leap into the unknown.', 'It’s all a mystery from here.', 'It’s all guesswork now.', 'It’s anyone’s guess from here.', 'It’s like trying to read tea leaves.', 'It’s out of my hands now.', 'It’s up in the air.', 'Let’s pretend I know what I’m doing.', 'No idea what’s next on the agenda.', 'No one knows what’s next.', 'Plot twist incoming!', 'Stay tuned, I guess?', 'The next chapter is a mystery.', 'The next move is beyond me.', 'The path ahead is shrouded.', 'The possibilities are endless.', 'The road ahead is unclear.', 'The story’s unwritten from here.', 'This is where I stop understanding.', 'To be continued… I hope?', 'We are stepping into the unknown.', 'We’ll just have to wait and see.', 'We’ll see what unfolds.', 'We’re in the wild now.', 'We’re in uncharted territory now.', 'We’re off script now.', 'We’ve entered the gray area.', 'Well, this is where my crystal ball breaks.', 'Whatever happens, happens.', 'Your guess is as good as mine.',], 
     clawingBackSynonym: ['battling their way back', 'bouncing back', 'breaking through the wall', 'charging back', 'chipping away at the deficit', 'clawing their way back', 'clawing out of quicksand', 'climbing uphill', 'closing the gap', 'coming back swinging', 'coming up swinging', 'crawling out of the hole', 'cutting into the lead', 'digging deep for a comeback', 'digging themselves out', 'dragging themselves back', 'emerging from the shadows', 'fighting tooth and nail', 'finding light in the chaos', 'finding their rhythm', 'forcing a shift in momentum', 'forcing their way into the game', 'getting back into the game', 'getting their groove back', 'grinding against gravity', 'grinding their way forward', 'hanging in there', 'hauling themselves up', 'holding on for dear life', 'hustling back into the fight', 'kicking their way out', 'making a run at it', 'making noise again', 'mounting a comeback', 'piecing themselves together', 'pressing forward', 'pulling themselves from the edge', 'pulling themselves up', 'pushing against the odds', 'pushing through the pain', 'rallying from the ruins', 'refusing to be buried', 'refusing to fade away', 'refusing to fold', 'refusing to go down', 'refusing to go quietly', 'refusing to stay down', 'reigniting the fight', 'resurrecting their chances', 'ripping through resistance', 'rising from the ashes', 'rising in defiance', 'scrambling for momentum', 'scraping for every inch', 'scratching back into contention', 'shaking off the rust', 'showing their grit', 'sparking a revival', 'staying alive in the fight', 'stealing momentum', 'stoking the comeback flames', 'storming back', 'storming the gates', 'surging from behind', 'swinging with everything they’ve got', 'taking it one step at a time', 'taking the fight to the wire', 'tearing their way back', 'trying to turn the tide', 'turning pain into progress', 'working their way back',],
     notMadJustDisappointedSynonym: ['Expectations are dangerous, but still.', 'I can’t hide my disappointment.', 'I can’t pretend this doesn’t bother me.', 'I didn’t think we were capable of this.', 'I didn’t think we’d stoop this low.', 'I don’t even know how to respond.', 'I expected better.', 'I need space after that.', 'I need time to think about this.', 'I thought we were better than this.', 'I wish I could say I’m shocked.', 'I wish I didn’t care — it’d be easier.', 'I’m disappointed, not furious.', 'I’m more hurt than mad.', 'I’m not angry — just let down.', 'I’m not angry, I’m just deeply saddened.', 'I’m not even mad — just tired.', 'I’m not even sure what to say right now.', 'I’m not furious — just disillusioned.', 'I’m not surprised — just saddened.', 'I’m not upset, just really disappointed.', 'I’m not yelling because it’s worse than that.', 'I’m sad. Just really, really sad.', 'I’m struggling to process this.', 'I’ve seen all I need to.', 'If that’s what you’re proud of, okay.', 'It’s hard to explain how much this hurts.', 'It’s hard when someone you care about chooses wrong.', 'It’s not rage, it’s resignation.', 'Let’s talk when I’m less disappointed.', 'My silence says enough.', 'Sometimes silence says more than words.', 'That broke my heart a little.', 'That hit me harder than I expected.', 'That’s... unfortunate.', 'This hurts more than it angers me.', 'This isn’t about anger. It’s about trust.', 'This isn’t how I imagined things would go.', 'This isn’t what I hoped for.', 'Trust is fragile.', 'You’ve given me a lot to reflect on.',],
     goodBaseballTeamsSynonym: ['check out clubs that know how to win.', 'check out teams that are not owned by the Monforts.', 'check out teams that did not finish with 119 losses.', 'check out teams that did not not flirt with being the worst team of all time.', 'check out teams that had a run differential greater than -424.', 'discover what separates the great teams from, well, you know.', 'experience baseball with playoff intensity.', 'experience baseball with some real starting pitching.', 'experience baseball with teams that can hit away from Coors Field.', 'experience what championship baseball feels like.', 'get a feel for playoff-caliber baseball.', 'observe great bullpen management.', 'observe how winning baseball teams operate.', 'observe teams that knows how to win games.', 'observe teams with championship aspirations.', 'observe the pace and poise of confident teams.', 'see baseball played the right way.', 'see great defense win ballgames.', 'see how a deep bench contributes to wins.', 'see how a team executes the fundamentals.', 'see how baseball is meant to be played.', 'see how defense wins championships.', 'see how good teams control the tempo of the game.', 'see how talent and preparation come together.', 'see how top-tier baseball is played.', 'see the difference a good team makes on the field.', 'see the importance of fundamentals in action.', 'see the kind of team that goes deep in October.', 'see what great baseball looks like.', 'see what it takes to win at this level.', 'see what makes baseball beautiful when played right.', 'see why these teams are at the top of the standings.', 'see winning teams that play the long game.', 'understand what makes a baseball team successful.', 'watch championship culture in action.', 'watch how disciplined teams play clean baseball.', 'watch how good teams bounce back from losses.', 'watch how good teams execute under stress.', 'watch how top baseball teams play.', 'watch the synergy of a championship teams.', 'witness baseball teams firing on all cylinders.', 'witness high-level baseball at its finest.', 'witness textbook baseball execution.', 'witness the confidence of top-tier ballclubs.',],



     
  }
  return all;
}













